### ISSUE TITLE
Azure / Docker materiaaliin pikku tarkennus

### ISSUE THREAD

**Issue by ristoxxx** [haagahelia/swd4tn023#3]
Törmäsin omissa harjoituksissani tilanteeseen että sain mukavasti Doker kontin azureen mutta luotaessa kontista web appia viimeisellä sivulla ilmeni validation error. Syyksi paljastui että windows ja linux palveluita ei voi sijoittaa samaan laskutusryhmään ja oli käyttänyt samaa ryhmää jossa oli jo windows palvelu. Virheilmoitus validation error ei olut kaikkein selkein näin aloittelijan näkökulmasta ja johti ensin ajatukset siihen suuntaan että itse kontissa tai sen siitämisessä palvelimelle on mennyt jotain pieleen. Kurrssilla voisi olla mainita että windows ja linux palvelut tulee sijoittaa eri laskutusryhmään azuressa.

Ohje virheen toistamiseksi. Luo kurssin ohjeilla docker kontti ja siirä se azureen. sen jälkeen yritä luoda siirtämästäsi docker kontista web app siten että sijoitat sen samaan laskutusryhmään(luontisivun toinen syöttökenttä) jokun windows palvelun kanssa. Luontiprosessi etenee normaalisti viimeiselle sivulle jossa se feilaa validation erroriin.

**Comment by swd1tn002** [comment]
Kiitos ehdotuksesta @ristoxxx! Lisäsin uuden kappaleen ["Linux and Windows resource groups"](https://github.com/haagahelia/swd4tn023/tree/master/07_azure#linux-and-windows-resource-groups) materiaalin alkuosaan.
